//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Практика_ТРЗБД_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avtobysi
    {
        public int ID_Avtobysa { get; set; }
        public int ID_Statusa { get; set; }
        public string Nomer_avtobysa { get; set; }
        public string God_vipyska { get; set; }
        public int Kolvo_mest { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual Reisi Reisi { get; set; }
    }
}
