//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Практика_ТРЗБД_.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bus_CompanyEntities : DbContext
    {
        public Bus_CompanyEntities()
            : base("name=Bus_CompanyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Avtobysi> Avtobysi { get; set; }
        public virtual DbSet<Bileti> Bileti { get; set; }
        public virtual DbSet<Dolzhnosti> Dolzhnosti { get; set; }
        public virtual DbSet<Gorod> Gorod { get; set; }
        public virtual DbSet<Operacii_> Operacii_ { get; set; }
        public virtual DbSet<Passazhiri> Passazhiri { get; set; }
        public virtual DbSet<Poezdka> Poezdka { get; set; }
        public virtual DbSet<Reisi> Reisi { get; set; }
        public virtual DbSet<Remont> Remont { get; set; }
        public virtual DbSet<Sotrydniki> Sotrydniki { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Voditelskoe_ydostoverenie> Voditelskoe_ydostoverenie { get; set; }
    }
}
