//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Практика_ТРЗБД_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reisi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reisi()
        {
            this.Bileti = new HashSet<Bileti>();
            this.Poezdka = new HashSet<Poezdka>();
        }
    
        public int ID_Reisa { get; set; }
        public int ID_Avtobysa { get; set; }
        public int ID_Sotrydnika { get; set; }
        public System.TimeSpan Vremia_v_pyti { get; set; }
        public string Distancia { get; set; }
    
        public virtual Avtobysi Avtobysi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bileti> Bileti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Poezdka> Poezdka { get; set; }
        public virtual Sotrydniki Sotrydniki { get; set; }
    }
}
