//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Практика_ТРЗБД_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remont
    {
        public int ID_Remonta { get; set; }
        public int ID_Avtobysa { get; set; }
        public int ID_Sotrudnika { get; set; }
        public System.DateTime Data_nachalo { get; set; }
        public System.DateTime Data_konec { get; set; }
    
        public virtual Sotrydniki Sotrydniki { get; set; }
    }
}
