//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Практика_ТРЗБД_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voditelskoe_ydostoverenie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voditelskoe_ydostoverenie()
        {
            this.Sotrydniki = new HashSet<Sotrydniki>();
        }
    
        public int ID_Ydostoverenia { get; set; }
        public string Seria { get; set; }
        public string Nomer { get; set; }
        public System.DateTime Data_vidachi { get; set; }
        public System.DateTime Srok_deistvia { get; set; }
        public int Stazh_vozhdenia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sotrydniki> Sotrydniki { get; set; }
    }
}
